startup_mode = "Fullscreen"
"window.opacity" = 0.95

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x676767"
blue = "0x49a4f8"
cyan = "0x5ffdff"
green = "0x5ff967"
magenta = "0xff76ff"
red = "0x00ff3e"
white = "0xfeffff"
yellow = "0xfefb67"

[colors.normal]
black = "0x2e2e2e"
blue = "0x47a0f3"
cyan = "0x00c5c7"
green = "0x00c200"
magenta = "0xc930c7"
red = "0xeb4129"
white = "0xc7c7c7"
yellow = "0xc7c400"

[colors.primary]
background = "0x000000"
foreground = "0xc4c5b5"

[font]
size = 14

[font.bold]
family = "Liberation Mono for Powerline"
style = "Bold"

[font.italic]
family = "Liberation Mono for Powerline"
style = "Italic"

[font.normal]
family = "Liberation Mono for Powerline"
style = "Regular"

[mouse]
hide_when_typing = true

[mouse.double_click]
threshold = 300

[mouse.triple_click]
threshold = 300
